"""RUNBOOK.md: the operator's exact commands (PLAN §2.5, §13).

ecsodus never runs these. Each mutating step is preceded by the ecsodus check that gates it.
Step 5 (teardown) is only emitted with ``--i-understand-teardown-is-unverified`` until the real
AWS end-to-end run has settled the open questions (PLAN §6); steps 6 and 7 are always emitted.
"""

from __future__ import annotations

import shlex

from ecsodus import __version__
from ecsodus.emit.patches import PatchSet
from ecsodus.mappers.fates import IMPORT, MANUAL_CLEANUP, MigrationPlan
from ecsodus.model import ADDONS, APP, ENV, ENV_ADDONS, STACKSET_INSTANCE, WORKLOAD

UNVERIFIED = (
    "> **UNVERIFIED TEARDOWN.** Step 5 has not yet been validated against real AWS. Two\n"
    "> CloudFormation behaviours are still open: whether `DeletionPolicy: Retain` on a\n"
    "> `Custom::*` resource suppresses its Delete handler, and how a policy-only change set is\n"
    "> reported. See PLAN §6. Until the ecsodus end-to-end run passes, treat step 5 as expert-only.\n"
)


def q(s: str) -> str:
    return shlex.quote(s)


def _params(names: list[str]) -> str:
    return " ".join(f"ParameterKey={q(n)},UsePreviousValue=true" for n in names)


def render(plan: MigrationPlan, patches: PatchSet, *, include_teardown: bool,
           out_dir: str = ".", inventory_path: str = "inventory.json") -> str:
    inv = plan.inventory
    lines: list[str] = []
    w = lines.append
    handoff = {n for n, s in plan.stacks.items() if s.handoff}
    roots = [s for s in inv.stacks.values()
             if s.name in handoff and s.kind in (APP, ENV, WORKLOAD)]
    order = {APP: 0, ENV: 1, WORKLOAD: 2}
    roots.sort(key=lambda s: (order[s.kind], s.name))
    envs_arg = " ".join(f"--env {q(e)}" for e in inv.envs)

    w(f"# Runbook: migrate Copilot app `{inv.app}` to Terraform (adopt in place)\n")
    w(f"Generated by ecsodus {__version__} for account `{inv.account}`, region `{inv.region}`, "
      f"from an inventory captured at {inv.captured_at}.\n")
    w(UNVERIFIED)
    w("Run every command from the directory that holds the generated Terraform "
      f"(`{out_dir}`). Stop at the first failing check. Nothing here is run by ecsodus.\n")
    kept = {n: s for n, s in plan.stacks.items() if not s.handoff}
    if kept:
        w("## Stacks that stay on Copilot\n")
        w("These stacks are **kept**. Nothing in this runbook touches them, and step 5 stops "
          "before any shared stack they depend on.\n")
        for n, s in sorted(kept.items()):
            w(f"- `{n}`: {'; '.join(s.kept_because)}")
        w("")
    if plan.closure_errors:
        w("## STOP: closure check failed\n")
        w("`ecsodus generate` refused to produce a complete hand-off. Fix these first:\n")
        for e in plan.closure_errors:
            w(f"- {e}")
        return "\n".join(lines) + "\n"

    # 1 -------------------------------------------------------------------------------
    w("## 1. Freeze\n")
    w("- Stop all `copilot deploy`, `copilot env deploy`, `copilot app upgrade` and pipeline "
      "runs for this app until the runbook is finished.")
    w("- Record each stack's last update time:\n")
    w("```bash")
    for s in roots:
        w(f"aws cloudformation describe-stacks --stack-name {q(s.name)} "
          "--query 'Stacks[0].LastUpdatedTime' --output text")
    w("```\n")

    # 2 -------------------------------------------------------------------------------
    w("## 2. Protect\n")
    w("Take backups, test a restore, and turn on deletion protection where it is off. This "
      "creates CloudFormation drift on purpose; the retain patch in step 3 does not revert it "
      "because the template property is unchanged.\n")
    w("```bash")
    protected = False
    for rp in plan.imports():
        live = inv.live.get(rp.physical_id or "", {})
        if rp.type == "AWS::RDS::DBCluster":
            protected = True
            w(f"aws rds create-db-cluster-snapshot --db-cluster-identifier {q(rp.physical_id or '')}"
              f" --db-cluster-snapshot-identifier {q((rp.physical_id or '') + '-ecsodus')}")
            if not live.get("DeletionProtection"):
                w(f"aws rds modify-db-cluster --db-cluster-identifier {q(rp.physical_id or '')} "
                  "--deletion-protection --apply-immediately")
        elif rp.type == "AWS::RDS::DBInstance" and not live.get("DeletionProtection"):
            protected = True
            w(f"aws rds modify-db-instance --db-instance-identifier {q(rp.physical_id or '')} "
              "--deletion-protection --apply-immediately")
        elif rp.type == "AWS::DynamoDB::Table":
            protected = True
            w(f"aws dynamodb create-backup --table-name {q(rp.physical_id or '')} "
              f"--backup-name {q((rp.physical_id or '') + '-ecsodus')}")
            if not live.get("DeletionProtectionEnabled"):
                w(f"aws dynamodb update-table --table-name {q(rp.physical_id or '')} "
                  "--deletion-protection-enabled")
        elif rp.type == "AWS::S3::Bucket":
            versioning = (live.get("Versioning") or {}).get("Status")
            if versioning != "Enabled":
                protected = True
                w(f"aws s3api put-bucket-versioning --bucket {q(rp.physical_id or '')} "
                  "--versioning-configuration Status=Enabled")
        elif rp.type == "AWS::EFS::FileSystem":
            protected = True
            w(f"# EFS {rp.physical_id}: confirm an AWS Backup recovery point exists and restores")
    if not protected:
        w("# no stateful resources need protection changes")
    w("```\n")
    w("Then refresh the inventory so the generated Terraform matches the new settings:\n")
    w("```bash")
    w(f"ecsodus inventory --app {q(inv.app)} {envs_arg} -o {q(inventory_path)}")
    w(f"ecsodus generate {q(inventory_path)} --out {q(out_dir)}")
    w("```\n")

    # 3 -------------------------------------------------------------------------------
    w("## 3. Retain patches\n")
    w("Every resource in every handed-off stack gets `DeletionPolicy: Retain` and "
      "`UpdateReplacePolicy: Retain`, with no exceptions. Patched templates are in "
      "`retain-patches/`. After this step, no stack delete can remove or empty anything.\n")
    w("Upload the patched templates (nested stacks are patched through their parent's "
      "`TemplateURL`):\n")
    w("```bash")
    for name, p in sorted(patches.stacks.items()):
        if name in handoff and not p.already_retained:
            w(f"aws s3 cp retain-patches/{q(name)}.yml s3://{patches.bucket}/{p.key}")
    w("```\n")
    for ss_name, res in sorted(patches.stackset.items()):
        ss = inv.stacksets[ss_name]
        if not any(inv.stacks[n].kind == STACKSET_INSTANCE for n in handoff if n in inv.stacks):
            continue
        w(f"### 3a. StackSet `{ss_name}`\n")
        w("StackSets have no change sets. Diff offline, update with zero failure tolerance, "
          "then verify every instance stack.\n")
        w("```bash")
        w(f"aws cloudformation describe-stack-set --stack-set-name {q(ss_name)} "
          "--query StackSet.TemplateBody --output text > stackset-current.yml")
        w(f"ecsodus check --template-diff stackset-current.yml retain-patches/stackset-{ss_name}.yml")
        caps = " ".join(ss.capabilities)
        w(f"aws cloudformation update-stack-set --stack-set-name {q(ss_name)} "
          f"--template-body file://retain-patches/stackset-{ss_name}.yml "
          f"--parameters {_params(sorted(ss.parameters))} "
          + (f"--capabilities {caps} " if caps else "")
          + f"--administration-role-arn {q(ss.administration_role_arn)} "
          f"--execution-role-name {q(ss.execution_role_name)} "
          "--operation-preferences FailureToleranceCount=0,MaxConcurrentCount=1")
        w("# wait until the operation and every instance report SUCCEEDED:")
        w(f"aws cloudformation list-stack-set-operations --stack-set-name {q(ss_name)} "
          "--query 'Summaries[0].Status'")
        for n in sorted(handoff):
            if inv.stacks[n].kind == STACKSET_INSTANCE:
                w(f"ecsodus verify-retain --app {q(inv.app)} --stack {q(n)}")
        w("```\n")
        _ = res
    w("### 3b. Stacks\n")
    w("For each stack below, in order. A stack marked *already retained* is skipped after "
      "`verify-retain` confirms it.\n")
    for s in roots:
        p = patches.stacks[s.name]
        w(f"#### `{s.name}` ({s.kind})\n")
        if p.already_retained:
            w("Already retained. Confirm and skip:\n")
            w("```bash")
            w(f"ecsodus verify-retain --app {q(inv.app)} --stack {q(s.name)}")
            w("```\n")
            continue
        caps = " ".join(s.capabilities)
        cs = f"ecsodus-retain-{p.result.sha256[:12]}"
        w("```bash")
        w(f"aws cloudformation create-change-set --stack-name {q(s.name)} "
          f"--change-set-name {cs} --template-url {q(p.url)} "
          "--include-nested-stacks --include-property-values "
          f"--parameters {_params(sorted(s.parameters))}"
          + (f" --capabilities {caps}" if caps else ""))
        w(f"aws cloudformation wait change-set-create-complete --stack-name {q(s.name)} "
          f"--change-set-name {cs} || true")
        w(f"aws cloudformation describe-change-set --stack-name {q(s.name)} "
          f"--change-set-name {cs} > cs-{s.name}.json")
        if p.children:
            w("# nested change sets (one per patched addons stack):")
            w(f"for id in $(jq -r '.Changes[].ResourceChange | select(.ResourceType==\"AWS::"
              f"CloudFormation::Stack\") | .ChangeSetId // empty' cs-{s.name}.json); do")
            w(f"  aws cloudformation describe-change-set --change-set-name \"$id\" "
              f"> \"cs-{s.name}-nested-${{id##*/}}.json\"")
            w("done")
        w(f"ecsodus check --changeset cs-{s.name}*.json --manifest ecsodus-manifest.json "
          f"--stack {q(s.name)}")
        w(f"aws cloudformation execute-change-set --stack-name {q(s.name)} "
          f"--change-set-name {cs}")
        w(f"aws cloudformation wait stack-update-complete --stack-name {q(s.name)}")
        w(f"ecsodus verify-retain --app {q(inv.app)} --stack {q(s.name)}")
        w("```\n")
        w("If `check --changeset` reports **empty**: the stack may already be retained "
          "(`verify-retain` passes: skip it), or CloudFormation treated the policy-only change "
          "as a no-op. In that case regenerate with `--metadata-fallback` and add "
          "`--allow-metadata-key` to the check.\n")
    w("Finally, re-inventory and regenerate. The patch changed every stack's `LastUpdatedTime`, "
      "and regeneration must produce the same Terraform (PLAN §13.9):\n")
    w("```bash")
    w(f"ecsodus inventory --app {q(inv.app)} {envs_arg} -o {q(inventory_path)}")
    w(f"ecsodus generate {q(inventory_path)} --out regen && "
      f"diff -r -x ecsodus-manifest.json -x retain-patches -x RUNBOOK.md -x REPORT.md . regen")
    w("```\n")

    # 4 -------------------------------------------------------------------------------
    w("## 4. Import into Terraform\n")
    w("```bash")
    w("cp backend.hcl.example backend.hcl   # edit the bucket name first")
    w("terraform init -backend-config=backend.hcl")
    w("terraform plan -out tf-import.plan")
    w("terraform show -json tf-import.plan > plan-import.json")
    w("ecsodus check plan-import.json --manifest ecsodus-manifest.json --phase import")
    w("terraform apply tf-import.plan")
    w("terraform state list > state.txt")
    w("ecsodus check --state state.txt --manifest ecsodus-manifest.json")
    w("terraform plan -out tf-steady.plan && terraform show -json tf-steady.plan > plan-steady.json")
    w("ecsodus check plan-steady.json --manifest ecsodus-manifest.json --phase steady")
    w("(umask 077 && terraform state pull > checkpoint.tfstate)")
    w("```\n")
    w("**Rollback before step 5:** `terraform state rm` each imported address "
      "(listed in `ecsodus-manifest.json`). CloudFormation still owns everything, and the "
      "retain patches are harmless. **After step 5 there is no rollback to Copilot.**\n")
    w("**After the migration, image rollouts belong to your deploy tool** (ecspresso, or CI "
      "that registers task-definition revisions). Terraform ignores `task_definition` and "
      "`desired_count` on services. When a new revision replaces the imported one, delete the "
      "`aws_ecs_task_definition` resource block **and** its `import` block in the same change "
      "that adds:\n")
    w("```hcl")
    for rp in plan.imports():
        if rp.type == "AWS::ECS::TaskDefinition" and rp.tf_address:
            w(f"removed {{\n  from = {rp.tf_address}\n  lifecycle {{\n    destroy = false\n  }}\n}}")
    w("```\n")

    # 5 -------------------------------------------------------------------------------
    w("## 5. Teardown of Copilot stacks\n")
    if not include_teardown:
        w("Not emitted. Regenerate with `--i-understand-teardown-is-unverified` to include "
          "the teardown commands (see the banner at the top).\n")
    else:
        w("Delete only stacks with no remaining consumers, in this order. Before each delete, "
          "`verify-retain` must pass.\n")
        w("```bash")
        for name in plan.teardown:
            s = inv.stacks[name]
            if s.kind == STACKSET_INSTANCE:
                continue
            w(f"ecsodus verify-retain --app {q(inv.app)} --stack {q(name)}")
            if s.kind in (ADDONS, ENV_ADDONS):
                w(f"# {name} was orphaned when its parent was deleted (its wrapper is retained)")
            w(f"aws cloudformation delete-stack --stack-name {q(name)}")
            w(f"aws cloudformation wait stack-delete-complete --stack-name {q(name)}")
        instances = [n for n in plan.teardown if inv.stacks[n].kind == STACKSET_INSTANCE]
        for ss_name, ss in sorted(inv.stacksets.items()):
            if not instances:
                break
            accounts = sorted({i["account"] for i in ss.instances})
            regions = sorted({i["region"] for i in ss.instances})
            w(f"aws cloudformation delete-stack-instances --stack-set-name {q(ss_name)} "
              f"--accounts {' '.join(accounts)} --regions {' '.join(regions)} --retain-stacks")
            for n in instances:
                w(f"ecsodus verify-retain --app {q(inv.app)} --stack {q(n)}   # patch only if this fails")
                w(f"aws cloudformation delete-stack --stack-name {q(n)}")
                w(f"aws cloudformation wait stack-delete-complete --stack-name {q(n)}")
            w(f"aws cloudformation delete-stack-set --stack-set-name {q(ss_name)}")
        w("```\n")
    if plan.teardown_stops_at:
        w(f"**STOP before `{plan.teardown_stops_at}`**: "
          f"{'; '.join(plan.stacks[plan.teardown_stops_at].kept_because)}. Do not delete it or "
          "any later shared stack.\n")

    # 6 -------------------------------------------------------------------------------
    w("## 6. Verify\n")
    w("```bash")
    w("terraform plan -out tf-final.plan && terraform show -json tf-final.plan > plan-final.json")
    w("ecsodus check plan-final.json --manifest ecsodus-manifest.json --phase steady")
    w("```\n")
    w("A zero-change plan after refresh proves that every imported resource still exists and "
      "matches. Then read your sentinel data back, and delete the Copilot-internal leftovers "
      "(retained by the patch, now unowned):\n")
    for rp in plan.resources:
        if rp.fate == MANUAL_CLEANUP and rp.physical_id and rp.stack in plan.teardown:
            w(f"- `{rp.type}` `{rp.physical_id}` (from `{rp.stack}/{rp.logical_id}`)")
    w("\nRetained resources keep their `aws:cloudformation:*` tags. The AWS provider ignores "
      "`aws:` tags, so they cause no drift, and you may leave them.\n")

    # 7 -------------------------------------------------------------------------------
    w("## 7. Never, after migrating\n")
    w("- Never run `copilot app delete`, `copilot env delete`, `copilot env deploy` or "
      "`copilot app upgrade` against a retained or migrated stack. They re-render templates "
      "without the Retain policies and can modify imported resources.")
    w("- After a partial migration, only `copilot svc deploy` of *unmigrated* workloads is "
      "allowed. Afterwards, re-run `ecsodus verify-retain`.")
    w("")
    _ = IMPORT
    return "\n".join(lines) + "\n"
