"""Write the Terraform project and the hand-off manifest (PLAN §2.4, ADR-0006).

Output layout (``--out``):

    versions.tf            terraform/provider constraints (bounded) and the S3 backend
    backend.hcl.example    encrypted, locked S3 state (copy to backend.hcl)
    provider.tf            region + allowed_account_ids guard
    <stack>.tf             one file per handed-off stack: resources + import blocks
    ecsodus-manifest.json  import set, retain-patch hashes, teardown order (read by `check`)
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ecsodus import __version__
from ecsodus.emit import hcl
from ecsodus.emit.hcl import Block, Raw
from ecsodus.emit.patches import PatchSet
from ecsodus.mappers.fates import IMPORT, MigrationPlan
from ecsodus.model import now_iso, write_sensitive

TERRAFORM_CONSTRAINT = "~> 1.10"
AWS_PROVIDER_CONSTRAINT = "~> 6.41"
MANIFEST = "ecsodus-manifest.json"


def header(source: str) -> str:
    return (
        f"# Generated by ecsodus {__version__} from {source}.\n"
        "# Arguments are literal values read from the deployed stack and live state, so the\n"
        "# first plan is import-only. Do not edit before `ecsodus check --phase import` passes.\n"
    )


def _with_lifecycle(body: hcl.Body, prevent_destroy: bool) -> hcl.Body:
    if not prevent_destroy:
        return body
    out: hcl.Body = []
    merged = False
    for k, v in body:
        if k == "lifecycle" and isinstance(v, Block):
            v = Block([("prevent_destroy", True), *[(a, b) for a, b in v.body
                                                    if a != "prevent_destroy"]])
            merged = True
        out.append((k, v))
    if not merged:
        out.append(("lifecycle", Block([("prevent_destroy", True)])))
    return out


def render_stack(plan: MigrationPlan, stack_name: str) -> str:
    parts = [header(f"CloudFormation stack {stack_name}")]
    for rp in plan.by_stack(stack_name):
        if rp.fate != IMPORT or rp.spec is None or rp.tf_address is None:
            continue
        tf_type, name = rp.tf_address.split(".", 1)
        parts.append(f"# {rp.logical_id} ({rp.type})"
                     + (f" — {rp.reason}" if rp.reason else ""))
        for note in rp.spec.notes:
            parts.append(f"# note: {note}")
        parts.append(hcl.block("import", (), [
            ("to", Raw(rp.tf_address)),
            ("id", rp.spec.import_id),
        ]))
        body = _with_lifecycle(rp.spec.body, rp.spec.stateful)
        parts.append(hcl.block("resource", (tf_type, name), body))
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def render_versions() -> str:
    return header("ecsodus") + hcl.block("terraform", (), [
        ("required_version", TERRAFORM_CONSTRAINT),
        ("required_providers", Block([
            ("aws", {"source": "hashicorp/aws", "version": AWS_PROVIDER_CONSTRAINT}),
        ])),
        ("backend", Block([], ("s3",))),
    ]) + "\n"


def render_backend_example(plan: MigrationPlan) -> str:
    inv = plan.inventory
    return (
        "# Copy to backend.hcl and run: terraform init -backend-config=backend.hcl\n"
        "# State contains plaintext task-definition environment values: keep it encrypted.\n"
        'bucket       = "REPLACE-with-your-state-bucket"\n'
        f'key          = "ecsodus/{inv.app}/terraform.tfstate"\n'
        f'region       = "{inv.region}"\n'
        "encrypt      = true\n"
        "use_lockfile = true\n"
    )


def render_provider(plan: MigrationPlan) -> str:
    inv = plan.inventory
    return header("ecsodus") + hcl.block("provider", ("aws",), [
        ("region", inv.region),
        ("allowed_account_ids", [inv.account]),
    ]) + "\n"


def manifest(plan: MigrationPlan, patches: PatchSet) -> dict[str, Any]:
    inv = plan.inventory
    return {
        "ecsodus_version": __version__,
        "generated_at": now_iso(),
        "app": inv.app,
        "account": inv.account,
        "region": inv.region,
        "inventory_captured_at": inv.captured_at,
        "stack_last_updated": {s.name: s.last_updated for s in inv.stacks.values()},
        "imports": [
            {"address": r.tf_address, "id": r.spec.import_id, "stack": r.stack,
             "logical_id": r.logical_id, "type": r.type, "stateful": r.spec.stateful}
            for r in plan.imports() if r.spec is not None
        ],
        "handoff_stacks": [n for n, s in plan.stacks.items() if s.handoff],
        "kept_stacks": {n: s.kept_because for n, s in plan.stacks.items() if not s.handoff},
        "teardown": plan.teardown,
        "teardown_stops_at": plan.teardown_stops_at,
        "patch_bucket": patches.bucket,
        "retain_patches": {
            n: {"sha256": p.result.sha256, "key": p.key, "url": p.url,
                "already_retained": p.already_retained,
                "nested": {lid: {"stack": child, "sha256": patches.stacks[child].result.sha256}
                           for lid, child in p.children.items()}}
            for n, p in patches.stacks.items()
        },
        "stackset_patches": {n: r.sha256 for n, r in patches.stackset.items()},
    }


def write_project(plan: MigrationPlan, patches: PatchSet, out: Path) -> list[Path]:
    out.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    def put(rel: str, text: str) -> None:
        p = out / rel
        write_sensitive(p, text)
        written.append(p)

    put("versions.tf", render_versions())
    put("provider.tf", render_provider(plan))
    put("backend.hcl.example", render_backend_example(plan))
    for name, sp in plan.stacks.items():
        if sp.handoff and any(r.fate == IMPORT for r in plan.by_stack(name)):
            put(f"{name}.tf", render_stack(plan, name))
    put(MANIFEST, json.dumps(manifest(plan, patches), indent=2) + "\n")
    put(".gitignore", "inventory*.json\nplan*.json\nstate*.txt\n*.tfstate*\n.terraform/\n"
        "backend.hcl\n")
    return written
